### ISSUE TITLE
How make energy Use readable for home assistant

### ISSUE THREAD

**Issue by uowis** [chomupashchuk/ariston-aqua-remotethermo-home-assistant#29]
Is there a way to put the value of consumption into Hass energy dashboard ?
Thanks for your plugin working since 2 year now and fully use !

**Comment by surenz** [comment]
I've opened a while ago request for more nice energy measurement but it's a bit of hassle to implement in the code. So I thought how to do it on HA template level and this is what I figured out for the daily energy:
```
 - platform: template
   sensors:
     boiler_daily_energy:
        friendly_name: "Boiler daily energy"
        value_template: >-
            {% if is_state('binary_sensor.aqua_ariston_online', 'on') %}
                {% set ns = namespace(total = 0) %}
                {% for count in range(0,12) %}
                    {% set count = count+1 %}
                    {% set current =  state_attr('sensor.aqua_ariston_energy_use_in_the_last_day','Period' + count|string)  %}
                    {% set ns.total = ns.total + current  %}
                {% endfor %}
                {{ns.total| round(2)}}
            {% endif %}
        availability_template: "{{ state_attr('sensor.aqua_ariston_energy_use_in_the_last_day','Period1') != None}}"
        unit_of_measurement: "kWh"
```
The other entities (weekly, monthly) can be made with another sensors as well if wanted.
The purpose of this template is to have historical data which can be reset at midnight and have a real energy measurement for a day and not like now the 24h interval energy consumption (which in my opinion is useless for data gathering).

**Comment by uowis** [comment]
Oh ty ! I will test this template sensor !

**Comment by chomupashchuk** [comment]
In another integration (https://github.com/chomupashchuk/ariston-remotethermo-home-assistant-v2/blob/master/custom_components/ariston/sensor.py) you may see different class being specified for energy use and that class works better with energy statistics like "today".
I do not maintain this integration, but if someone would make updates on separate branch and make a pull request, I could approve it.

**Comment by ZsBT** [comment]
I have a Lydos Wifi 100. I'll check this out, maybe adding state_class and last_reset to the sensors would help.

**Comment by uowis** [comment]
I finally choose to create te entity with caclul with time to heat : 
```
  - trigger:
      - platform: time_pattern
        # This will update every minutes
        minutes: "*"
    sensor:
      - name: "Ariston Velis Energy Timebased"
        state:  >
          {% if is_number(states("sensor.ariston_velis_energy_timebased")) %}
            {{ states("sensor.ariston_velis_energy_timebased") | float + is_state("binary_sensor.aqua_ariston_heating", "on") | abs * 1/60 * 1.5  }}
          {% endif %}
        unit_of_measurement: 'kWh'    
        device_class: energy 
        state_class: total_increasing
```
